### ISSUE TITLE
Unable to add forfeits to the Schedule

### ISSUE THREAD

**Issue by TsukoteAmie** [cory2067/gtsosu#112]
On the BTT schedule, for some reason I can't submit forfeit scores. When I click ok, it just loads eternally.
Does this have something to do with the Stats? That there's no mp link to pull scores from?

![image](https://user-images.githubusercontent.com/28514601/168191878-6fd6757c-4548-4104-a39a-77178890ca37.png)

**Comment by cory2067** [comment]
yeah that's exactly what's happening, it tries to update the stats and confused that the mp link is empty
i'll update this to skip over match stats if mp link is empty

**Comment by TsukoteAmie** [comment]
thank you thank you

**Comment by cory2067** [comment]
Fixed in c2c6c918692774b21b4877a6fd089f6302594ec5
