### ISSUE TITLE
Add links to all GTS socials on the front page

### ISSUE THREAD

**Issue by Briesmas** [cory2067/gtsosu#142]
Add links with icons to all the GTS related stuff: Twitter, Youtube, main Twitch channel, Discord server, Bandcamp and I guess Osu Wiki page

**Comment by Kasumiikun** [comment]
Gonna send every link just for the sake of them being faster to find

**Comment by Kasumiikun** [comment]
This was fairly appropriately addressed through the website's redesign a while back, only missing osu! wiki but not that big of a deal.
Closing.
