### ISSUE TITLE
Allow qualifier lobbies registrations to be locked

### ISSUE THREAD

**Issue by Kasumisama** [cory2067/gtsosu#191]
As most GTS tournaments tend to use a specific deadline to get players to register to lobbies, actually enforcing on the website the fact that they cannot move whatsoever after a specific date might be good?

We somehow haven't needed that in past GTS tourneys, but EGCS just made me need to actually screenshot lobbies and enforce "no players are allowed to move now", so ehh.... Would be good as a safety measure. Not high priority though, as EGCS' qualifiers are already starting, and next GTS tourney is in 2025.

**Comment by Chupalika** [comment]
thought of two solutions:
- add a toggle to the top of the schedules page (visible to admins only) that toggles whether lobbies are locked
- add a date picker instead that determines the deadline to sign up to a lobby, which will automatically prevent changes from non-admins when that deadline is passed
I think I'm leaning towards the second option

**Comment by Kasumiikun** [comment]
Second option works better yeah, it's better to automatize stuff as much as we can.
