### ISSUE TITLE
Improve language dropdown menu

### ISSUE THREAD

**Issue by cory2067** [cory2067/gtsosu#38]
![image](https://user-images.githubusercontent.com/8433005/156509012-5333f719-17cb-44e4-8cbc-c31551b24804.png)
This is pretty gross. Instead, we should have these options change based on which tourney is currently being viewed.

The code for this is in Navbar.js, where there's a hardcoded list of language options. 
Maybe we could populate the list of available languages based off what files are in the client/src/content directory

**Comment by Briesmas** [comment]
I'd like to add something to this.
Change the "Language" on the top menu to a more recognizable term/icon by everyone. Some ppl don't seem to know this word. I believe either displaying the current selected language (English, ...) or a flag (like osu! website) would make it clearer.
