### ISSUE TITLE
Succesful entry validation message

### ISSUE THREAD

**Issue by Briesmas** [cory2067/gtsosu#47]
Either a short text under the "Role"/"Custom flag" thing or a ticket(?) appearing on the bottom right for example when you add staff/teams to indicate it was successful. This is really low prio btw but sometimes I double check when I add stuff because of a potential typo so this would be a nice QoL.

**Comment by cory2067** [comment]
More details on this:

There are some forms that don't have any indication of success or failure. I think Team creation already has error messages, so maybe Bries was remembering wrong. But the staff list definitely is missing those messages:

In `TourneyStaff.js`, when you submit a new staff member but the username doesn't exist (e.g. typo), then it'll fail but you won't see an error message.

Add some error handling for that API call -- if it succeeds or fails you can use import `message` from antd and show a message with these functions:
```
message.success("Staff member added");
message.error("Couldn't add staff member");
```

**Comment by fajar13k** [comment]
Is this suppose to be only `TourneyStaff.js` job, or I can check the whole thing and see if respective files does have error/success msgs or not?

**Comment by cory2067** [comment]
It would be cool if you could check the whole thing, I think there might be other places that need error/success messages

**Comment by cory2067** [comment]
Done in #72 i think
